# Generated by Django 4.0.4 on 2022-05-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='amount',
            field=models.IntegerField(default=' 0'),
            preserve_default=False,
        ),
    ]
