# Generated by Django 4.0.4 on 2022-05-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_remove_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Event',
            new_name='Eventtitle',
        ),
    ]
