# Generated by Django 4.0.4 on 2022-05-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_rename_event_booking_eventtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Name',
            new_name='user',
        ),
    ]
