# Generated by Django 4.0.4 on 2022-05-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_alter_booking_options_rename_name_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ordered_date',
            new_name='booked_date',
        ),
    ]
